name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering for testing

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Cache pip dependencies

      - name: Install dependencies
        run: |
          pip install pandas ruff

      - name: Run Ruff checks
        run: |
          ruff check .

      - name: Execute script and generate result.json
        run: |
          python execute.py > result.json

      - name: Create artifact directory
        run: |
          mkdir _site
          mv result.json _site/result.json

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
